import { v4 as uuid } from "uuid";
import {
  AmazonProduct,
  attractive_woman,
  bookSelf,
  camera,
  cesar_chocolate,
  coat,
  comfortChair,
  cpuCooler,
  curology,
  electric_toy_car,
  fantechController,
  footballBoot,
  gameController,
  gamingMonitor,
  gucciBag,
  gucci_perfume,
  ideapadGaming,
  jacket,
  mechanicalKeyboard,
  ps5Slim,
  speakers,
} from "../assets/ProductImgIndex";

const todaysSales = [
  {
    id: uuid(),
    imgPath: gameController,
    productName: "havit hv-g92 gamepad",
    marketPrice: 160,
    discountPercent: 40,
    isWished: true,
    rating: 5,
    review: 88,
    category: "Gaming",
  },
  {
    id: uuid(),
    imgPath: mechanicalKeyboard,
    productName: "AK-900 wired keyboard",
    marketPrice: 1160,
    discountPercent: 35,
    isWished: false,
    rating: 4,
    review: 75,
    category: "Gaming",
  },
  {
    id: uuid(),
    imgPath: gamingMonitor,
    productName: "IPS LCD gaming monitor",
    marketPrice: 400,
    discountPercent: 30,
    isWished: false,
    rating: 5,
    review: 99,
    category: "Gaming",
  },
  {
    id: uuid(),
    imgPath: comfortChair,
    productName: "S-series comform chair",
    marketPrice: 400,
    discountPercent: 25,
    isWished: false,
    rating: 4.5,
    review: 99,
    category: "Gaming",
  },
];

const bestSellingProducts = [
  {
    id: uuid(),
    imgPath: coat,
    productName: "the north coat",
    marketPrice: 360,
    discountPercent: 20,
    isWished: false,
    rating: 5,
    review: 65,
    category: "Gaming",
  },
  {
    id: uuid(),
    imgPath: gucciBag,
    productName: "gucci duffle bag",
    marketPrice: 1160,
    discountPercent: 20,
    isWished: false,
    rating: 4.5,
    review: 65,
    category: "Gaming",
  },
  {
    id: uuid(),
    imgPath: cpuCooler,
    productName: "RGB liquid CPU cooler",
    marketPrice: 170,
    discountPercent: 20,
    isWished: false,
    rating: 4.5,
    review: 65,
    category: "Gaming",
  },
  {
    id: uuid(),
    imgPath: bookSelf,
    productName: "small bookSelf",
    marketPrice: 360,
    discountPercent: 0,
    isWished: false,
    rating: 5,
    review: 65,
    category: "Gaming",
  },
  {
    id: uuid(),
    imgPath: AmazonProduct,
    productName: "Amazon Product",
    marketPrice: 360,
    discountPercent: 0,
    isWished: false,
    rating: 5,
    review: 65,
    category: "Gaming",
  },
];

const newArrivals = [
  {
    id: 1,
    productName: "playstation 5",
    description: "Black and White version of the PS5 coming out on sale.",
    imgPath: ps5Slim,
    category: "Gaming",
  },
  {
    id: 2,
    productName: "women's collections",
    description: "Featured woman collections that give you another vibe.",
    imgPath: attractive_woman,
    category: "Gaming",
  },
  {
    id: 3,
    productName: "speakers",
    description: "Amazon wireless speakers",
    imgPath: speakers,
    category: "Gaming",
  },
  {
    id: 4,
    productName: "perfume",
    description: "gucci intense OUD EDP",
    imgPath: gucci_perfume,
    category: "Gaming",
  },
];

const ourProducts = [
  {
    id: uuid(),
    imgPath: cesar_chocolate,
    productName: "breed dry dog food",
    marketPrice: 100,
    discountPercent: 0,
    isWished: false,
    rating: 3,
    review: 35,
    category: "Gaming",
  },
  {
    id: uuid(),
    imgPath: camera,
    productName: "canon EOS DSLR camera",
    marketPrice: 360,
    discountPercent: 0,
    isWished: false,
    rating: 4,
    review: 95,
    category: "Gaming",
  },
  {
    id: uuid(),
    imgPath: ideapadGaming,
    productName: "asus FHD gaming laptop",
    marketPrice: 700,
    discountPercent: 0,
    isWished: false,
    rating: 5,
    review: 325,
    category: "Gaming",
  },
  {
    id: uuid(),
    imgPath: curology,
    productName: "curology product set",
    marketPrice: 500,
    discountPercent: 0,
    isWished: false,
    rating: 4,
    review: 145,
    category: "Gaming",
  },
  {
    id: uuid(),
    imgPath: electric_toy_car,
    productName: "kids electric car",
    marketPrice: 960,
    discountPercent: 0,
    isWished: false,
    rating: 5,
    review: 65,
    category: "HeadPhones",
  },
  {
    id: uuid(),
    imgPath: footballBoot,
    productName: "jr. zoom soccer cleat",
    marketPrice: 360,
    discountPercent: 0,
    isWished: false,
    rating: 5,
    review: 35,
    category: "HeadPhones",
  },
  {
    id: uuid(),
    imgPath: fantechController,
    productName: "GP11 Shooter USB Gamepad",
    marketPrice: 660,
    discountPercent: 0,
    isWished: false,
    rating: 4.5,
    review: 55,
    category: "Gaming",
  },
  {
    id: uuid(),
    imgPath: jacket,
    productName: "quilted satin jacket",
    marketPrice: 660,
    discountPercent: 0,
    isWished: false,
    rating: 4.5,
    review: 55,
    category: "Gaming",
  },
  {
    id: uuid(),
    imgPath: cesar_chocolate,
    productName: "breed dry dog food",
    marketPrice: 100,
    discountPercent: 0,
    isWished: false,
    rating: 3,
    review: 35,
    category: "Gaming",
  },
  {
    id: uuid(),
    imgPath: camera,
    productName: "canon EOS DSLR camera",
    marketPrice: 360,
    discountPercent: 0,
    isWished: false,
    rating: 4,
    review: 95,
    category: "Gaming",
  },
  {
    id: uuid(),
    imgPath: ideapadGaming,
    productName: "asus FHD gaming laptop",
    marketPrice: 700,
    discountPercent: 0,
    isWished: false,
    rating: 5,
    review: 325,
    category: "Gaming",
  },
  {
    id: uuid(),
    imgPath: curology,
    productName: "curology product set",
    marketPrice: 500,
    discountPercent: 0,
    isWished: false,
    rating: 4,
    review: 145,
    category: "Gaming",
  },
  {
    id: uuid(),
    imgPath: electric_toy_car,
    productName: "kids electric car",
    marketPrice: 960,
    discountPercent: 0,
    isWished: false,
    rating: 5,
    review: 65,
    category: "Gaming",
  },
  {
    id: uuid(),
    imgPath: footballBoot,
    productName: "jr. zoom soccer cleat",
    marketPrice: 360,
    discountPercent: 0,
    isWished: false,
    rating: 5,
    review: 35,
    category: "Gaming",
  },
  {
    id: uuid(),
    imgPath: fantechController,
    productName: "GP11 Shooter USB Gamepad",
    marketPrice: 660,
    discountPercent: 0,
    isWished: false,
    rating: 4.5,
    review: 55,
    category: "Gaming",
  },
  {
    id: uuid(),
    imgPath: jacket,
    productName: "quilted satin jacket",
    marketPrice: 660,
    discountPercent: 0,
    isWished: false,
    rating: 4.5,
    review: 55,
    category: "Gaming",
  },
];

export { bestSellingProducts, newArrivals, ourProducts, todaysSales };
